#!/bin/bash
#
# (C) Copyright 2016 Hardkernel Co,.Ltd
#

bpart=`mount | grep media/boot | awk '{print $1}' | sed s/"p1"//g`

if [[ $bpart == "/dev/mmcblk"* ]]; then
    UBOOT=/usr/share/n2_uboot/u-boot.bin
    dd if=$UBOOT of=$bpart conv=fsync,notrunc bs=512 seek=1
    sync
fi